export enum ErrorMessages {
  EmailInUse = 'This email is already in use',
  EnvironmentNotFound = 'Environment not found',
  ProjectNotFound = 'Project not found',
  UserNotFound = 'User not found',
  InvalidEmail = 'Invalid Email',
  RequiredField = 'This field is required',
  Unauthorized = 'Unauthorized access',
  Forbidden = 'Forbidden access',
  InvalidCredentials = 'Invalid credentials',
  InvalidEmailOrPass = 'Invalid email or password',
  InvalidToken = 'Invalid Token',
  InternalError = 'An internal error ocurred, try again',
  MissingAuthSecret = 'Auth secret not found',
  EmailTemplateNotFound = 'Email template not found',
  MaxLength = 'Max length exceeded',
  InvalidUser = 'Invalid user',
  CannotChangeOwnStatus = 'You cannot change your own status',
  CannotDeleteOwnUser = 'You cannot delete your own user',
  UserAlreadyAcceptedInvitation = 'User already accepted invitation',
  UserIsNotActive = 'User is not active',
  InvalidDomainFormat = 'Invalid domain format',
}
